In [1]:
import yfinance as yf
import pandas as pd

In [2]:
ticker = yf.Ticker('AAPL')

In [3]:
ticker.options

('2026-07-20',
 '2026-07-22',
 '2026-07-24',
 '2026-07-27',
 '2026-07-29',
 '2026-07-31',
 '2026-08-07',
 '2026-08-14',
 '2026-08-21',
 '2026-08-28',
 '2026-09-18',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [4]:
expiry = ticker.options[0]
expiry

'2026-07-20'

In [5]:
chain = ticker.option_chain(expiry)

In [6]:
type(chain)

yfinance.ticker.Options

In [7]:
chain.calls.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260720C00215000,2026-07-14 18:50:30+00:00,215.0,100.19,116.70,120.70,0.000000,0.000000,NaN,1,3.125490,True,REGULAR,USD
1,AAPL260720C00220000,2026-07-14 18:50:30+00:00,220.0,95.22,111.75,115.70,0.000000,0.000000,NaN,1,2.989260,True,REGULAR,USD
2,AAPL260720C00225000,2026-07-14 18:50:54+00:00,225.0,90.25,106.65,110.50,0.000000,0.000000,2.0,0,2.788577,True,REGULAR,USD
3,AAPL260720C00230000,2026-07-16 15:08:36+00:00,230.0,100.22,101.75,105.45,0.690002,0.693261,16.0,16,2.642582,True,REGULAR,USD
4,AAPL260720C00235000,2026-07-06 15:57:48+00:00,235.0,79.00,96.75,100.45,0.000000,0.000000,NaN,0,2.516605,True,REGULAR,USD

In [8]:
calls = chain.calls
calls.columns

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       'impliedVolatility', 'inTheMoney', 'contractSize', 'currency'],
      dtype='str')

In [9]:
puts = chain.puts
puts.columns

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       'impliedVolatility', 'inTheMoney', 'contractSize', 'currency'],
      dtype='str')

In [10]:
calls.dtypes

contractSymbol                      str
lastTradeDate        datetime64[s, UTC]
strike                          float64
lastPrice                       float64
bid                             float64
ask                             float64
change                          float64
percentChange                   float64
volume                          float64
openInterest                      int64
impliedVolatility               float64
inTheMoney                         bool
contractSize                        str
currency                            str
dtype: object

In [11]:
row = calls.iloc[0]
row

contractSymbol             AAPL260720C00215000
lastTradeDate        2026-07-14 18:50:30+00:00
strike                                   215.0
lastPrice                               100.19
bid                                      116.7
ask                                      120.7
change                                     0.0
percentChange                              0.0
volume                                     NaN
openInterest                                 1
impliedVolatility                      3.12549
inTheMoney                                True
contractSize                           REGULAR
currency                                   USD
Name: 0, dtype: object

In [12]:
from optionanalytics.models.option import OptionQuote
from optionanalytics.models.enums import OptionType

In [13]:
quote = OptionQuote(
    option_type=OptionType.CALL,
    strike=row["strike"],
    bid=row["bid"],
    ask=row["ask"],
    last_price=row["lastPrice"],
    volume=row["volume"],
    open_interest=row["openInterest"],
    last_trade_time=row["lastTradeDate"]
)

In [16]:
quote

OptionQuote(option_type=<OptionType.CALL: 'call'>, strike=np.float64(215.0), bid=np.float64(116.7), ask=np.float64(120.7), last_price=np.float64(100.19), volume=np.float64(nan), open_interest=np.int64(1), last_trade_time=Timestamp('2026-07-14 18:50:30+0000', tz='UTC'))

In [17]:
for row in calls.itertuples(): # faster than iterrows()
    print(row)
    break

Pandas(Index=0, contractSymbol='AAPL260720C00215000', lastTradeDate=Timestamp('2026-07-14 18:50:30+0000', tz='UTC'), strike=215.0, lastPrice=100.19, bid=116.7, ask=120.7, change=0.0, percentChange=0.0, volume=nan, openInterest=1, impliedVolatility=3.1254904675292967, inTheMoney=True, contractSize='REGULAR', currency='USD')

In [18]:
records = calls.to_dict("records")

In [20]:
records[0:2]

[{'contractSymbol': 'AAPL260720C00215000',
  'lastTradeDate': Timestamp('2026-07-14 18:50:30+0000', tz='UTC'),
  'strike': 215.0,
  'lastPrice': 100.19,
  'bid': 116.7,
  'ask': 120.7,
  'change': 0.0,
  'percentChange': 0.0,
  'volume': nan,
  'openInterest': 1,
  'impliedVolatility': 3.1254904675292967,
  'inTheMoney': True,
  'contractSize': 'REGULAR',
  'currency': 'USD'},
 {'contractSymbol': 'AAPL260720C00220000',
  'lastTradeDate': Timestamp('2026-07-14 18:50:30+0000', tz='UTC'),
  'strike': 220.0,
  'lastPrice': 95.22,
  'bid': 111.75,
  'ask': 115.7,
  'change': 0.0,
  'percentChange': 0.0,
  'volume': nan,
  'openInterest': 1,
  'impliedVolatility': 2.989260339355469,
  'inTheMoney': True,
  'contractSize': 'REGULAR',
  'currency': 'USD'}]

In [21]:
calls["volume"].isna().sum()

np.int64(7)

In [22]:
calls[calls["volume"].isna()].head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260720C00215000,2026-07-14 18:50:30+00:00,215.0,100.19,116.70,120.70,0.0,0.0,NaN,1,3.125490,True,REGULAR,USD
1,AAPL260720C00220000,2026-07-14 18:50:30+00:00,220.0,95.22,111.75,115.70,0.0,0.0,NaN,1,2.989260,True,REGULAR,USD
4,AAPL260720C00235000,2026-07-06 15:57:48+00:00,235.0,79.00,96.75,100.45,0.0,0.0,NaN,0,2.516605,True,REGULAR,USD
5,AAPL260720C00240000,2026-07-06 15:57:48+00:00,240.0,74.00,91.75,95.50,0.0,0.0,NaN,0,2.407719,True,REGULAR,USD
6,AAPL260720C00245000,2026-07-09 18:16:41+00:00,245.0,70.12,86.75,90.45,0.0,0.0,NaN,2,2.270024,True,REGULAR,USD

In [23]:
calls["bid"].eq(0).sum()

np.int64(5)

In [24]:
calls["openInterest"].eq(0).sum()

np.int64(4)

In [25]:
calls[["bid", "ask", "lastPrice", "volume", "openInterest"]].describe()

              bid         ask   lastPrice        volume  openInterest
count   48.000000   48.000000   48.000000     41.000000     48.000000
mean    35.369583   37.527708   32.926875   3264.365854    530.333333
std     35.853403   37.231334   31.096849   7775.221215    923.797766
min      0.000000    0.020000    0.010000      1.000000      0.000000
25%      1.865000    2.075000    1.992500     16.000000      4.750000
50%     26.025000   28.850000   27.395000     61.000000     52.500000
75%     54.850000   58.575000   56.355000   1921.000000    723.000000
max    116.700000  120.700000  100.220000  40861.000000   3979.000000

In [27]:
for row in calls.itertuples(): # faster than iterrows()
    print(row.strike, row.volume)
    break

215.0 nan

In [28]:
for row in calls.itertuples(index=False): # faster than iterrows()
    print(row.strike, row.volume)
    break

215.0 nan